version: "3.8"

services:

  scl-automation:

    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: scl-automation

    volumes:
      - ../input:/app/input
      - ../output:/app/output
      - ../archive:/app/archive
      - ../logs:/app/logs

    restart: unless-stopped